## Filebeat configuration
## https://github.com/elastic/beats/blob/master/deploy/docker/filebeat.docker.yml
#

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/mrt/臺北捷運每日分時各站OD流量統計資料_*.csv # 10601 ~ now - 2 
  tags: ["mrt"]

processors:
  - add_cloud_metadata: ~

output.logstash:
  enabled: true
  hosts: ['logstash:5044']
  index: traffic
## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
#

http.enabled: true
http.host: 0.0.0.0
